name: Build goclip (Windows)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - name: Install MSYS2 (MinGW-w64) for CGO
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config

      - name: Add MinGW to PATH
        shell: pwsh
        run: echo "C:\msys64\mingw64\bin" >> $Env:GITHUB_PATH

      - name: Set build environment
        shell: pwsh
        run: |
          echo "CGO_ENABLED=1" >> $Env:GITHUB_ENV
          echo "GOOS=windows" >> $Env:GITHUB_ENV
          echo "GOARCH=amd64" >> $Env:GITHUB_ENV
          echo "CC=x86_64-w64-mingw32-gcc" >> $Env:GITHUB_ENV
          if ("${{ github.ref_type }}" -eq "tag") {
            $v = "${{ github.ref_name }}"
          } else {
            $sha = "${{ github.sha }}".Substring(0,7)
            $v = "dev-$sha"
          }
          echo "APP_VERSION=$v" >> $Env:GITHUB_ENV

      - name: Go mod download
        run: go mod download

      - name: Install goversioninfo (for embedding icon)
        shell: pwsh
        run: |
          go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest

      # Create versioninfo.json so goversioninfo has explicit config (incl. icon)
      - name: Generate versioninfo.json
        shell: pwsh
        run: |
          $v = "${{ env.APP_VERSION }}".TrimStart('v')
          if ($v -notmatch '^\d+\.\d+\.\d+$') { $v = '0.0.0' }
          $json = @{
            FixedFileInfo = @{
              FileVersion    = "$v.0"
              ProductVersion = "$v.0"
              FileFlagsMask  = "3f"
              FileFlags      = "00"
              FileOS         = "040004"
              FileType       = "01"
              FileSubType    = "00"
            }
            StringFileInfo = @{
              FileDescription  = "goclip"
              InternalName     = "goclip"
              OriginalFilename = "goclip.exe"
              ProductName      = "goclip"
            }
            VarFileInfo = @{ Translation = @(1033,1200) }
            IconPath = "assets\\logo\\app.ico"
          } | ConvertTo-Json -Depth 6
          $json | Out-File -Encoding utf8 versioninfo.json

      - name: Generate Windows resources (icon + version -> resource.syso)
        shell: pwsh
        run: |
          $gv = Join-Path (go env GOPATH) 'bin/goversioninfo.exe'
          if (-not (Test-Path $gv)) { throw "goversioninfo not found at $gv" }
          Get-ChildItem -Filter "resource*.syso" -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
          & $gv -platform-specific -icon "assets/logo/app.ico"

      - name: Build goclip.exe (GUI, stripped)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          go build -trimpath -ldflags="-H=windowsgui -s -w" -o dist/goclip-windows-amd64.exe .

      - name: Package zip
        shell: pwsh
        run: |
          Compress-Archive -Path dist/goclip-windows-amd64.exe -DestinationPath dist/goclip-${Env:APP_VERSION}-windows-amd64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: goclip-${{ env.APP_VERSION }}-windows-amd64
          path: |
            dist/goclip-windows-amd64.exe
            dist/goclip-${{ env.APP_VERSION }}-windows-amd64.zip
          if-no-files-found: error

      - name: Publish GitHub Release (tagged)
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            dist/goclip-windows-amd64.exe
            dist/goclip-${{ env.APP_VERSION }}-windows-amd64.zip
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          allowUpdates: true
          replacesArtifacts: true
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
